apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lingua-app
  namespace: lingua-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: lingua.cachefly.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lingua-app
            port:
              number: 80
  tls:
  - hosts:
    - lingua.cachefly.site
    secretName: lingua-app-tls
