apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lingua-app
  namespace: lingua-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: lingua.cachefly.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lingua-app
                port:
                  number: 80
