apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgBZ1Ypfs4RcMs13Ybw2k5WzwdqhlZGYhJSZtG7thFMiPqbduXPen1z6Vxqk8FKHtLy5DWH6TKR8t0ZxKQGkuxkUsG4B4YBiOeTF5b0qcwz0pNPKxaKSzWlfCskTB/5W5JVutZLyF0LPOo3u3QDYV5svGManjl9jgoM0ZaOqdEfhtv3FtR8R0yhEp/tWpu7bxcg4pSU7UqSln/jST0TRpYVZrU5OMD3RaJtfPxX5t3E04duA2pWebRsqDWfQGN01xbda8KkVSbYRywYIfdrjSTstWbPEtsWzZchyH7a1lwMz7oE0zaencWNZQHEj+q4IfapC4MqsOhtqlXUqp1VPxJgikzcB86QxDIrxESXL2dmSB8wW+nMhlIvXOM9XfL2odb/AVF7aOe9hndXVsfL/kV+R8jzPIS+27MOuHKTr2JKxw9sVutNZXA11s/NtQnq6fpKTohffxWSCzGtlbe7vZvZnWBDoB+HSjKzTFeYiYXf+Lo0VokUsoCE7xG1B0cCGlP+n1xkckeJ6yqLZG6lUUAjRqAF8PHB56A3o5JShxCXVmo4HSl29hIuxqO0dCqjhQlxjkF8E9GNMFtQCK7w96WjfU8yY7+Tt2pZbmPictureRemoved==
    chat-id: AgBAloKZilF52lQCC6mBcqcO3uM5v5mQTp6Vchf89E0jk0CsUpWTAUfDPy5xKwpOzJh9+uWwp0mQva2OgfwSZYUID6zstf7ZEgmL4IfaCqXQG+1x0edNC1Y9QhVXiVt3uOdE1bJxKnuUBSojHQPojbfHCv2pMJm9X0ye1MZEmvTjqWh8dwwI36rvQlcKDq1Txgc05rnOlrqOclC2GQJLFkSmVwA6eU6fUJbKAyuCg2Wdi1WbR6uC4hU4tW5VkfY2n0pS0gMHxYWpjwYl0D0clYiEIdAxn6FGtisBHKS2wnKVuNodII04Ec9ErktP6ao9gco6Vlab7vZPuRqo6FIzCb3lZTscTw===
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
    type: Opaque
