---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgBBYAELvf25AkeNpjQDxDDaIg9rM9yDsw/YoJEjcdMU7EYBGRkCJS1RQjAJENAxfHFaCw40ddeCNNN/OGnJ1HtAR1V64/BoY0OKhGDDcjoK2Ds2mVzM9csINu/zuLAeVhzTWaLgviByvCe38oXgsqByWbSACpKMo8c3cfhv9wOifQ0r+ZqWvWZksBdkxa/VlPvBqvnkVhdQy7hbL3rC/OtVRo8fTxVRImVZalWdL/chdV82YD/yqRrwPLDUM3gw9sGeIKNUsy9RC83ZiWCMNQOWOPsPjLUnu5J+27uAfOSwRfQUzkTsYqnTkkuT3/lqzLfFjLPnF3imYoAA+HTar9TBwSyOdBIsUgWosMllYqm8ls9P46PmmCxuViA7kthSNpTBk2Gx1RTyuTC1+c9a3bYw/nbgCeClConOKUajmpiaIuAHcg3lsQepz30pV6l5b/p9/a7gaNg7XkMbrcLzYOOiTNXi2V2yMJUZ35pmk7WSBdW8As4XoeQJt+Z34yFYXL40EzOBpH7gihp12tYp4y2ONIdDL5N2PRMaQw3kWQzPm1S5rS81b+NxNLcqy72N2/aeOojKa0FtETiP24nTrcE3CI1/CPk9EhYmftybuiz3jKrzaZnwvWKiZGQkqheeOBhvUwZPT66Zlz4icawjshLEDifglJfT+XFUK0NzGIvO/hTJ/2yIuPxH4vixcjLSokmvLVIh6Wc8C1JncsrJFQq+ALUG1s/n65MK30x8cVu79PBdIdW8Nf7Vy2MjkhGp
    chat-id: AgAXhNtt633tlmAGtDO77PrMTmGszDtwmyGpYjFsvFSnbt4EmQO+C0Nhc7p1A4dxsrRjhmzGrMrR99N+np2b5zod/r5uFXudhH0xrbyAwJXK2Yd56ur++TeSfS9DkruwhDEVowli8XrAkdxHoqGvku/Dc4jp6zaClOOjJgVMOQVBACgpuJ8DWFVwF87z+ANg5eMAfg/ZBJ3qgkROJxa1Ip0a/0gxevItjnlHjrn4MBy8oE1duVC25VFchhgspZnW66rXeYS1i6uHhtmbx8OhZEn9kWq4IORtl0FJ1kyVSATYof4Tdbwa0pI4YsR2t4EumlvTMqBvoOEkgiqSmqLAr3RZuCO57GwDqjRpeCsC09FogKzHaW45LTpGn5tXu4JP6+QzGX/tU4ofpe2rmv/ODCs5LV+BrGKHWgWinz3jHayxpTHBPp4ylmlDKORWUPz8RSX5R1aB/h9bqFL30PvNWQv1cHSkR+p5vvmhB5IYAv74Zv7XQWTbwSl/K3tBCjdCB2vOpyu0nFENxbCTnAGZHQBmuZwKZyGMcQoEKrpr01ZMUFjfuZRMBWzVle8gxZQEthVZhvbAsVcEvcGIuVHaQzUKNCiyQJ/JWQv2UOLLRHWfsOPL0gqk0LWLNcLwMMPc35b5j423WZKmn2CK9siWQ9XgewANTzczHBCuDKIb5KPtCIWKJuC0bcfzl0SVtmJvHIueO52bu21W2M0=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-telegram
      namespace: monitoring
    type: Opaque
