apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helmrelease.yaml
  - prometheus-rule-backend.yaml
  - prometheus-rule-postgres.yaml
  - alertmanager-telegram-secret-template.yaml
  - dashboards
