apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ../../apps/infra
  - ../../apps/adhd-app
  # Deprecated: Old lingua-app (commented out)
  # - ../../apps/frontend
  # - ../../apps/lingua-app
