apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: mywebadhd
  namespace: flux-system
spec:
  image: ghcr.io/mvulcu/testadhd
  interval: 1m
  secretRef:
    name: ghcr-secret

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: mywebadhd
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mywebadhd
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: "^(latest|main-.*)$"

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: mywebadhd
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: gitops-platform
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: Flux CD Bot
      messageTemplate: |
        [flux] Update ADHD app image

        Automation: {{ .AutomationObject }}

        Files updated:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{ . }}
        {{ end -}}
    push:
      branch: master
  update:
    path: "./apps/adhd-app"
    strategy: Setters
