apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adhd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - sealed-secret.yaml
  - image-automation.yaml

commonLabels:
  app: mywebadhd
  managed-by: flux
