apiVersion: v1
kind: Service
metadata:
  name: mywebadhd
  namespace: adhd
  labels:
    app: mywebadhd
spec:
  type: ClusterIP
  selector:
    app: mywebadhd
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
