apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lingua-app
resources:
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - sealed-secret.yaml
  - servicemonitor.yaml